config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :twitterposts, only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  root 'welcome_page#index'

  get '/signup' => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

end

app/models/relationship.rb
# == Schema Information
#
# Table name: relationships
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/twitterpost.rb
# == Schema Information
#
# Table name: twitterposts
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Twitterpost < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string
#

class User < ActiveRecord::Base
  before_save { |user| user.email = email.downcase }
  
  validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
	has_secure_password
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
	                  format: { with: VALID_EMAIL_REGEX }, 
	                  uniqueness: { case_sensitive: false }
  
  has_many :twitterposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Twitterpost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
    
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def self.search(search)
    if search
      where('name LIKE ?', "%#{search}%")
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
      unless logged_in?
        
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :logged_in_user

  def create
  	@user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
  	@user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/twitterposts_controller.rb
class TwitterpostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user,   only: :destroy
	def create
		@twitterpost = current_user.twitterposts.build(twitterpost_params)
    if @twitterpost.save
      flash[:success] = "TwitterPost created!"
      redirect_to root_url
    else
    	@feed_items = []
      render 'welcome_page/index'
    end
  end

  def destroy
  	@twitterpost.destroy
    flash[:success] = "TwitterPost deleted"
    redirect_to request.referrer || root_url
  end
  private

    def twitterpost_params
      params.require(:twitterpost).permit(:content)
    end
    def correct_user
      @twitterpost = current_user.twitterposts.find_by(id: params[:id])
      redirect_to root_url if @twitterpost.nil?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :following, :followers]
  
  def new
  	@user = User.new
  end
  def show
  	@user = User.find(params[:id])
  	@twitterposts = @user.twitterposts.paginate(page: params[:page], per_page: 15)
  end

  def create
  	@user = User.new(user_params)
    if @user.save
    	log_in @user
      flash[:success] = "Welcome to the Twitter!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.search(params[:search]).paginate(page: params[:page], per_page: 15)
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private 
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def index
    if logged_in?
      @twitterpost = current_user.twitterposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    session[:user_id] = user.id
  end
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def current_user?(user)
    user == current_user
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end


end

app/helpers/twitterposts_helper.rb
module TwitterpostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_page_helper.rb
module WelcomePageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>

        <ul class="nav nav-pills">
          <li><%= link_to "Twitter", root_path, id: "logo" %></li>

          <% if logged_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Log in", login_path %></li>
          <% end %>

        </ul>           
      </div>
    </div>
  </div>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %> 
      
    </div>
</body>
</html>

app/views/layouts/application.html1.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav pull-left">
        <li><%= link_to "Twitter", root_path, id: "logo" %></li>
        </ul>
          <ul class="nav pull-right"> 
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", '#' %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>           
      </div>
    </div>
  </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      
      <%= yield %> 
      
    </div>
</body>
</html>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="twitterposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_twitterpost_form.html.erb
<%= form_for(@twitterpost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new TwitterPost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "View my profile", current_user %></span>
<span><%= pluralize(current_user.twitterposts.count, "TwitterPost") %></span>

app/views/twitterposts/_twitterpost.html.erb
<li id="twitterpost-<%= twitterpost.id %>">
  
  <span class="user"><%= link_to twitterpost.user.name, twitterpost.user %></span>
  <span class="content"><%= twitterpost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(twitterpost.created_at) %> ago.
    <% if current_user?(twitterpost.user) %>
      <%= link_to "delete", twitterpost, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li> 
  <%= link_to user.name, user %> 
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>Users</h1>
<%= form_tag users_path, :method => 'get', :id => "users_search" do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", class: "btn btn-primary", :name => nil %>
  </p>
<% end %>
<p><%=link_to 'Clear', users_path %></p>

<%= will_paginate %>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %> 
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> 
      
      <%= f.label :name %>
      <%= f.text_field :name %> 
      
      <%= f.label :email %>
      <%= f.text_field :email %> 

      <%= f.label :password %>
      <%= f.password_field :password %>
      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>
      <%= f.submit "Create my account", class: "btn btn-primary" %> 
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>        
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.twitterposts.any? %>
      <h3>TwitterPosts (<%= @user.twitterposts.count %>)</h3>
      <ol class="twitterposts">
        <%= render @twitterposts %>
      </ol>
      <%= will_paginate @twitterposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "View my profile", @user %></span>
      <span><b>TwitterPosts:</b> <%= @user.twitterposts.count %></span>
    </section>
    <section class="stats">
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/welcome_page/index.html.erb
<% provide(:title, 'Welcome Twitter') %> <!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
</head>

<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="twitterpost_form">
        <%= render 'shared/twitterpost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Twitter Posts</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
	<body>
	  <div class="center hero-unit">
	    <h1>Welcome to Twitter</h1>    
	    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> </div>    
	</body>
	</html>
<% end %>